### ISSUE TITLE
Show version and commit-id for both MapStore and geOrchestra current build

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#401] opened 2021-07-01 10:08 UTC
As was done for cadastrapp extension in https://github.com/georchestra/mapstore2-cadastrapp/issues/113#issuecomment-834215074, it would be really useful to show the commit hash for the currently running version of mapstore2-georchestra, maybe along the version shown in the settings widget - currently showing `Version: geOrchestra-1.2.0` , while i'd expect maybe `Version: geOrchestra-1.2.0 (b79d7680)` with `b79d7680` a link pointing at https://github.com/georchestra/mapstore2-georchestra/commit/b79d7680 (which is my currently used version).

pretty sure @MaelREBOUX will agree with me :)

**Comment by MaelREBOUX** [comment] 2021-07-08 08:51
+100
I dream of that. I just write an issue and I can't know on which version I work.

**Comment by catmorales** [comment] 2021-07-12 08:15
I agree too

**Comment by offtherailz** [comment] 2021-11-09 14:03
The application should also indicate the commit of MapStore.

**Comment by dsuren1** [comment] 2021-11-17 07:27
@landryb @MaelREBOUX
The version of the geOrchestra is fetched from [version.txt](https://github.com/georchestra/mapstore2-georchestra/blob/master/version.txt), so I think we can have an entry for Mapstore version in the same file to later parse them in the `Version` component. Hope this is fine.

Link to commit of the both apps will be displayed next to each other as requested above.

**Comment by landryb** [comment] 2021-11-17 08:22
just to make sure we agree on things, what is in `version.txt` matches more or less the branch the build is from, right ? it always annoyed me to have a static version in it, which doesnt mean much when commits pile on top.

i agree that's a useful user-facing information, but it's not very precise (otherwise `version.txt` should get modified everytime a bugfix/feature is commited ?), what matters is the commit id, which can only be in a single branch anyway :)

maybe something along those lines ?
```
mapstore2-georchestra version: 1.2.x (b79d7680)
mapstore2 version: 2021.01.xx (7c299af9)
```

`1.2.x` and `2021.01.xx` could even be links pointing at (respectively) https://github.com/georchestra/mapstore2-georchestra/commits/1.2.x and https://github.com/geosolutions-it/MapStore2/commits/2021.01.xx so that we can see directly if we're on the last commit in the corresponding branches, or if there are new commits in the branch since the version we're using and an update is needed.

**Comment by dsuren1** [comment] 2021-11-17 09:06
@landryb 
> just to make sure we agree on things, what is in `version.txt` matches more or less the branch the build is from, right ?

Yes

> maybe something along those lines ?
> 
> ```
> mapstore2-georchestra version: 1.2.x (b79d7680)
> mapstore2 version: 2021.01.xx (7c299af9)
> ```
> 
> `1.2.x` and `2021.01.xx` could even be links pointing at (respectively) https://github.com/georchestra/mapstore2-georchestra/commits/1.2.x and https://github.com/geosolutions-it/MapStore2/commits/2021.01.xx so that we can see directly if we're on the last commit in the corresponding branches, or if there are new commits in the branch since the version we're using and an update is needed.

Sure, we can make this happen 👍

**Comment by dsuren1** [comment] 2021-11-17 09:22
@landryb 
Hope this is okay to proceed
![2021-11-17 14_52_51-geOrchestra Viewer](https://user-images.githubusercontent.com/26929983/142172834-a732e755-7dd0-49fc-bd72-72f5aef9caa7.jpg)

**Comment by landryb** [comment] 2021-11-17 09:46
yes that looks good, except i'd make sure to have the first line `MapStore2-geOrchestra` to stress the fact that its *the mapstore2 integration in geOrchestra* project, and not *the version of geOrchestra* itself, which so far doesnt follow the same release numbering scheme (eg `20.1.x`, `21.0.x`..), which will just confuse end users :)

@fvanderbiest @MaelREBOUX ?

**Comment by MaelREBOUX** [comment] 2021-11-17 10:37
Hello,

Seems good for me.
And +1 :  it is  `MapStore2-geOrchestra` which is needed to be clear.

Note : we will clarify the naming af the tags / versions tomorrow.

**Comment by dsuren1** [comment] 2021-11-18 10:20
Hi @MaelREBOUX

> Note : we will clarify the naming af the tags / versions tomorrow.

Kindly ley me know if you have any update on this

**Comment by offtherailz** [comment] 2021-11-18 11:08
Here the indication @dsuren1 

https://github.com/georchestra/mapstore2-georchestra/issues/422#issuecomment-972655220

Summarising something like this, correct? 
```
MapStore2-geOrchestra: 20.1.0 (abcde123)
MapStore2: 2021.02.xx (fghilm456)
```

**Comment by offtherailz** [comment] 2021-11-26 17:49
@dsuren1 build server doesn't recongize commands for get-url etc.. in git. 
https://build.geo-solutions.it/jenkins/view/MapStore2/job/GeOrchestra%20DEV%20Build/181/console

We should provide an alternative solution for this.

**Comment by landryb** [comment] 2021-11-29 08:31
Fwiw, successfully tested with https://github.com/georchestra/mapstore2-georchestra/actions/runs/1508196635, very clean result, as expected :) many thanks @dsuren1  !

![image](https://user-images.githubusercontent.com/3421760/143833377-52618a2c-8cf6-4f95-adbb-3a17ff6a8682.png)

**Comment by offtherailz** [comment] 2021-11-29 09:16
I'm going to commit a small change to make repo-URLs of MapStore and geOrchestra not derived from git commands but configurable from plugin (with the current URLs as defaults).
This because
-  With older version of git `get-url` command is not present (e.g. in our  build server). 
- I think that this way a more stable solution: People often customize their remotes, e.g. `origin` for their fork and `upstream` for the original one.

**Comment by landryb** [comment] 2022-01-14 09:45
fwiw, on a dev version i deployed to test my wmts printing fixes, i have a strange leading '+' for the ms2 commit link:

![image](https://user-images.githubusercontent.com/3421760/149494307-40952196-cfa1-43d6-98c9-d91345f6f618.png)

that leads to a broken link in https://github.com/geosolutions-it/MapStore2/commit/+be444d6e5c89ff1a96a055c06a31a7fc70443253

anybody else seeing this ? @catmorales @dsuren1 @offtherailz ?

**Comment by landryb** [comment] 2022-01-14 09:47
@offtherailz can this be some fallout from 507e3c0 that you added on top of what @dsuren1 did ?

**Comment by offtherailz** [comment] 2022-01-14 11:15
I think your submodule is not aligned.

Reading the code, that output is generated from `git submodule status` output string. From master i see this result
```
c87f5fa9e5e744abc209d7a5e33b4682e22f04d9 MapStore2 (2017.03.00-2436-gc87f5fa9e)
```

To this string is applied this line: https://github.com/georchestra/mapstore2-georchestra/pull/430/files#diff-4984793ad4f29daa9cd3a0e85b574e69b08b18a6930ef850a3fb46cc146cb181R55 

So the final result should be  `c87f5fa9e5e744abc209d7a5e33b4682e22f04d9`. 

Anyway if your git sub-module is not aligned (different hash from the one committed), it is indicated with a plus. This is probably the cause of the issue.

Here I did a test and changing the submodule reference (my git output is in italian, but I think it should be understandable). 
```
$ git statusSul branch master
Modifiche non nell'area di staging per il commit:
  (usa "git add <file>..." per aggiornare gli elementi di cui sarà eseguito il commit)
  (usa "git restore <file>..." per scartare le modifiche nella directory di lavoro)
        modificato:             MapStore2 (nuovi commit)

nessuna modifica aggiunta al commit (usa "git add" e/o "git commit -a")
$ git diff
diff --git a/MapStore2 b/MapStore2
index c87f5fa..3bffb31 160000
--- a/MapStore2
+++ b/MapStore2
@@ -1 +1 @@
-Subproject commit c87f5fa9e5e744abc209d7a5e33b4682e22f04d9
+Subproject commit 3bffb313c1fdddb3422b2e653b52dadaa43fec3d
$ git submodule status 
+3bffb313c1fdddb3422b2e653b52dadaa43fec3d MapStore2 (2017.03.00-2435-g3bffb313c)
```

**Comment by landryb** [comment] 2022-01-14 11:36
right, that ... makes sense, and is probably because i built from a wip unclean src dir. i was really wondering where this extra `+` could come from.. at least that is a red herring :)

**Comment by MaelREBOUX** [comment] 2022-04-05 08:45
what about this issue ? Can we close it ?

**Comment by catmorales** [comment] 2022-04-06 15:48
I reopen this issue because i don't understand why the mapstore2georchestra version  is not aligned with the branch used to deploy it.
On portail-test,  we have: 

Site : https://portail-test.sig.rennesmetropole.fr/
Version mapstore2-georchestra: https://github.com/georchestra/mapstore2-georchestra/commit/373726f89e47cca7e3bac68360d2a9c593545862
Tag docker image: 2021.02.xx on https://hub.docker.com/layers/mapstore2-georchestra/geosolutionsit/mapstore2-georchestra/

![image](https://user-images.githubusercontent.com/4659829/162014917-14bc94bc-2ad8-45b2-962a-698a29c16448.png)

**Closed** 2022-04-12 16:56 UTC
Labels: Priority: High, Task, Contract #3, New Feature
