### ISSUE TITLE
install failed - Can't resolve dependency react due to wrong nodejs version

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#396] opened 2021-06-16 13:59 UTC
Hi,

Caught today on `./build.sh` (get with `npm install` cmd) with master branch.

```
gaetan@debian:~/git/mapstore2-georchestra$ ./build.sh 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: georchestra@1.2.0
npm ERR! Found: react@16.10.1
npm ERR! node_modules/react
npm ERR!   react@"16.10.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0" from @geosolutions/react-joyride@1.10.2
npm ERR! node_modules/@geosolutions/react-joyride
npm ERR!   @geosolutions/react-joyride@"1.10.2" from the root project

```

https://github.com/georchestra/mapstore2-georchestra/blob/c4d5e107bd0c414191851897b56b5d91f3b00c45/package.json#L101

https://www.npmjs.com/package/@geosolutions/react-joyride

**Steps:**

1. git clone recursive
2. ./build.sh

**versions**
```
npm@7.15.1
Node.js v16.3.0.
```

**Comment by Gaetanbrl** [comment] 2021-06-16 14:11
Same with branche 1.2.x


**/root/.npm/eresolve-report.txt**
```
Could not resolve dependency:
peer react@"^0.14.0 || ^15.0.0" from @geosolutions/react-joyride@1.10.2
node_modules/@geosolutions/react-joyride
  @geosolutions/react-joyride@"1.10.2" from the root project


{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "16.10.1",
    "whileInstalling": {
      "name": "georchestra",
      "version": "1.2.0",
      "path": "/home/gaetan/git/mapstore2-georchestra"
    },
    "location": "node_modules/react",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "react",
        "spec": "16.10.1",
        "from": {
          "location": "/home/gaetan/git/mapstore2-georchestra"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "react",
    "spec": "16.10.1",
    "from": {
      "location": "/home/gaetan/git/mapstore2-georchestra"
    }
  },
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": "^0.14.0 || ^15.0.0",
    "error": "INVALID",
    "from": {
      "name": "@geosolutions/react-joyride",
      "version": "1.10.2",
      "whileInstalling": {
        "name": "georchestra",
        "version": "1.2.0",
        "path": "/home/gaetan/git/mapstore2-georchestra"
      },
      "location": "node_modules/@geosolutions/react-joyride",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "@geosolutions/react-joyride",
          "spec": "1.10.2",
          "from": {
            "location": "/home/gaetan/git/mapstore2-georchestra"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

**Comment by Gaetanbrl** [comment] 2021-06-16 14:42
```
npm@7.15.1
Node.js v16.3.0.
```

Well, nodejs > 14.x seems not fully compatible (react `16.10.1`  is not the correct version expected by @geosolutions/react-joyride, need `^0.14.0 || ^15.0.0`).


**solution :  Downgrade nodejs from 16.x to 14.x and build.sh works.**


```

# Uninstall nodejs 16.x
apt remove nodejs

# Install nodejs 14.x as suggested by mapstore2-georchestra doc
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs
```

More info about nodejs install wit linux, debian : 
https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions

**Comment by Gaetanbrl** [comment] 2021-06-16 15:18
Works in progress ;) @landryb

**Comment by Gaetanbrl** [comment] 2021-06-16 15:19
> maybe the doc should be updated to specify the max version for nodejs ?

I will create a new issue about doc but i could use this issue too.

**Comment by Gaetanbrl** [comment] 2021-06-16 15:38
> maybe the doc should be updated to specify the max version for nodejs ?

@landryb not sur what is the max version but if i follow this releases infos, 14.x is the max (16.x ==> dependency error, 15.x ==> deprecated).

https://github.com/nodejs/Release
```

root@debian:~# curl -fsSL https://deb.nodesource.com/setup_15.x | bash -

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 15.x is no longer actively supported!
```

**Comment by abakostar** [comment] 2021-08-11 14:08
Bonjour, je voulais savoir si vous avez trouvé la solution à votre problème car j'ai le même problème.
J'utilise node v14.17 et npm 7.20.3 et quand je clone mapstore à partir de Github voilà ce que j'ai au niveau de npm install :

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mapstore2@0.3.0
npm ERR! Found: react@16.10.1
npm ERR! node_modules/react
npm ERR!   react@"16.10.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0" from @geosolutions/react-joyride@1.10.2
npm ERR! node_modules/@geosolutions/react-joyride
npm ERR!   @geosolutions/react-joyride@"1.10.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by Gaetanbrl** [comment] 2021-08-11 14:17
Je pense que vous devez passer sur une version npm 6.x.

**Comment by Gaetanbrl** [comment] 2021-08-11 14:21
https://nodejs.org/dist/index.json
nodejs 14.x => npm 6.x ==> ✔️

nodejs 14.x => npm 7.x ==> ❌

**Comment by abakostar** [comment] 2021-08-11 19:44
Merci beaucoup. la solution marche bien.

**Comment by abakostar** [comment] 2021-08-23 10:23
Very thank you for your helping.
Cordialement
**ABOUBAKAR SIDDIKI**
**GIS Specialist, BI and EMIS Expert**
**Assistant Service Head* in Planning Unit of Ministry of Secondary
Education (MINESEC), CAMEROON*

**Comment by abakostar** [comment] 2021-08-23 10:24
Hello, I apologize for bothering you. I am looking for help and as I saw
that you react in the group, I wanted to write to you directly. In fact I
have this error in my configured Masptore version. To check if the error
does not come from my version, I downloaded the .war from the official site
and zipped printing module and when I deploy in my Tomcat 9.0 I still have
the same error.
I am using Geoserver 2.19.0 and I do not know if the error comes from there
but that would surprise me since the version that I am testing and without
change compared to that of the official site just that I copy them to my
file tomcat. Thanks for your help

here is the error message below:

Error on printing: Error while generating PDF:
org.mapfish.print.InvalidValueException: url has an invalid value:
/${configDir}/print_header.png at
org.mapfish.print.config.layout.ImageBlock.render(ImageBlock.java:87) at
org.mapfish.print.PDFUtils.createCell(PDFUtils.java:631) at
org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:616) at
org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:58)
at
org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183)
at
org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56)
at org.mapfish.print.config.layout.Page.render(Page.java:80) at
org.mapfish.print.config.layout.Layout.render(Layout.java:67) at
org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30)
at
org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:62)
at org.mapfish.print.MapPrinter.print(MapPrinter.java:184) at
org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:409)
at
org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:190)
at
org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:107)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) at
javax.servlet.http.HttpServlet.service(HttpServlet.java:733) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
at
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
at
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
at
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source) Caused by:
java.net.URISyntaxException: Illegal character in path at index 11:
/C:/Program Files/Apache Software Foundation/Tomcat
9.0/webapps/mapstore/printing/print_header.png at
java.net.URI$Parser.fail(Unknown Source) at
java.net.URI$Parser.checkChars(Unknown Source) at
java.net.URI$Parser.parseHierarchical(Unknown Source) at
java.net.URI$Parser.parse(Unknown Source) at java.net.URI.<init>(Unknown
Source) at
org.mapfish.print.config.layout.ImageBlock.render(ImageBlock.java:85) ...
37 more
Cordialement
**ABOUBAKAR SIDDIKI**
**GIS Specialist, BI and EMIS Expert**
**Assistant Service Head* in Planning Unit of Ministry of Secondary
Education (MINESEC), CAMEROON*


Le lun. 23 août 2021 à 12:23, Siddiki Aboubakar ***@***.***> a
écrit :

**Comment by Gaetanbrl** [comment] 2021-08-23 11:01
Hi @abakostar,

I think this error is not about this issue.

If you use MapStore2 **without** georchestra, please open an issue in the MapStore2 GitHub page : 
https://github.com/geosolutions-it/MapStore2/issues

If you have this error with Mapstore2-GeOrchestra, please open a new issue :
https://github.com/georchestra/mapstore2-georchestra/issues

In addition, i invite you to share more details about you'r install (env, link, whatever you want...).

**Comment by abakostar** [comment] 2021-08-23 11:45
thank you for your response. I use Mapstore2 and my environnement tools are
:

node 14 and npm 6.x
apache maven 3.8.2 and tomcat 9.0
openjdk 11.0.11
Geoserver 2.19.0
 the picture of error below
[image: image.png]

Cordialement
**ABOUBAKAR SIDDIKI**
**GIS Specialist, BI and EMIS Expert**
**Assistant Service Head* in Planning Unit of Ministry of Secondary
Education (MINESEC), CAMEROON*

**Closed** 2021-08-23 12:05 UTC
