### ISSUE TITLE
doesnt respect WMS 1.3/WMTS 1.0 spec ? failure to load layers from mapproxy

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#108] opened 2019-11-21 14:14 UTC
Maybe more a mapstore2 issue itself that a mapstore2-georchestra, but trying to load layers from a mapproxy 1.11 instance fails on 2 bits:
- it defaults to load `image/png` format even if the GetCapabilities only lists `image/jpeg` for the `GetMap` WMS formats - fine, i can still specify manually `image/jpeg` in the layer config
- it doesnt send the `styles` parameter in the `GetMap` requests, and the mapproxy server complains about it: 

```
<?xml version="1.0"?>
<ServiceExceptionReport version="1.3.0"
  xmlns="http://www.opengis.net/ogc"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opengis.net/ogc
http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
    <ServiceException>missing parameters ['styles']</ServiceException>
</ServiceExceptionReport>
```
same thing with WMTS 1.0 on the same server:
```
<?xml version="1.0"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd"
  version="1.0.0" xml:lang="en">
  <ows:Exception exceptionCode="NoApplicableCode">
    <ows:ExceptionText>missing parameters ['style']</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```
on a sidenote, i noticed the js was trying a `DescribeDomains` request type, which is AFAICT a geoserver vendor extension, and might not be liked by remote servers...i know mapproxy replies with a 500 code in that case.

All this can be tried against any mapproxy server, but i used our own https://tiles.craig.fr/ortho/service instance which is public.

**Comment by landryb** [comment] 2019-11-21 14:27
On a sidenote, no issue loading a WMS layer from a mapserver 7.2 server also using WMS 1.3.0, but in that case the js sends an empty `styles=` parameter in the `GetMap` query.

**Comment by landryb** [comment] 2019-11-21 14:30
afaict the `style` parameter is mandatory in a `GetTile` WMTS request

**Comment by landryb** [comment] 2019-11-21 17:03
managed to load a wms layer from mapproxy by adding it as a new background and adding an additional empty styles= string parameter, but that was awkward :)

**Comment by mbarto** [comment] 2020-01-27 16:51
@landryb as you mention, they are all MapStore2 defects, they should not be too difficult to fix.
We only need to check that the additional parameters (e.g empty style(s)) are not bothering other WMS/WMTS servers.

**Comment by mbarto** [comment] 2020-01-29 09:08
We opened a MapStore issue for this: https://github.com/geosolutions-it/MapStore2/issues/4810

**Comment by landryb** [comment] 2020-01-29 09:41
great, i'll make sure to test it once it's resolved & the submodule is updated in our project !

**Comment by landryb** [comment] 2020-02-14 08:32
I'm sorry but it doesnt seem properly fixed, i still can't load a WMS layer from https://tiles.craig.fr/ortho/service.

Using the defaults, it asks for image/jpeg (and sends an empty styles parameter) and the server replies:
```
    <ServiceException>Invalid request: invalid tile format, use mixed</ServiceException>
```

if i force it to use image/png, then i get the same error as  before since the styles param isnt sent:
```
    <ServiceException>missing parameters ['styles']</ServiceException>
```

**Comment by landryb** [comment] 2020-02-14 08:34
all the details of the service are available on the mapproxy "demo" service at http://tiles.craig.fr/ortho/demo/

loading the same layer via WMTS works fine though !

**Comment by francoperversi** [comment] 2020-02-14 08:57
mauro will look at it as soon as possible

**Comment by mbarto** [comment] 2020-02-21 17:11
Blocked by https://github.com/geosolutions-it/MapStore2/pull/4923

**Comment by mbarto** [comment] 2020-02-28 10:30
Waiting for https://github.com/geosolutions-it/MapStore2/pull/4939 merge

**Comment by francoperversi** [comment] 2020-03-03 16:50
@mbarto does the PR #4939 contains the fix for this issue? 
Or you was waiting the merge of this PR in order to fix this issue?

**Comment by mbarto** [comment] 2020-03-04 09:18
@landryb @francoperversi the fix above is in, so it can be tested.
Actually it looks like some of the layers in the sample WMS are problematic by themselves (maybe a misconfiguration in mapproxy) when used in tiled mode (they work instead in single tile mode).
This layer looks good: Orthophotographie Auvergne CRAIG/IGN 2016

Other ones have this weird error: Invalid request: invalid tile format, use mixed

Searching on the internet it looks like a bug / problem with mapproxy itself and cached tiles: https://github.com/mapproxy/mapproxy/issues/52

**Comment by landryb** [comment] 2020-03-05 07:47
> Other ones have this weird error: Invalid request: invalid tile format, use mixed

this one is a bit specific to mapproxy (and has nothing to do with mapproxy/mapproxy#52), as tiles for the 2018 layer are stored in 'mixed' format. It's not a misconfiguration serverside, i'll need to investigate why it fails with mapstore and mapfishapp, as interestingly, it works without issue in QGIS .. which does this request:
```
/ortho/service?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=833012,6402512,966488,6604988&SRS=EPSG:2154&WIDTH=384&HEIGH
T=583&LAYERS=ortho_2018&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96
```

this mixed format layer works fine via WMTS though, it's only via WMS that it fails. And it finally works via WMS too if i force mapstore to use a singletile.

so the 'only' case where this layer doesnt work is via WMS & tiled mode.

other than that i've successfully loaded other layers (with regular storage format) via WMS & WMTS, so i think this specific issue can be closed.

one thing that annoys me wrt image format, but might be a distinct issue.. mapstore always lists 5 hardcoded formats (png,png8,jpeg,gif,vnd.png-jpeg) instead of only listing the formats advertised in the GetCapabilities, thus leading to `<ServiceException code="InvalidFormat">unsupported image format` responses.

**Comment by mbarto** [comment] 2020-03-05 09:08
@landryb it works with QGIS because it's not using tiled mode, look at the request, width and height are not 256 x 256.
If you switch to single tile mode it also works in MapStore.
The issue is probably only visible when you load the tiles from the cache (and so in tiled mode)

**Closed** 2020-03-06 09:42 UTC
Labels: Accepted, Priority: Medium, User feedback
