### ISSUE TITLE
[geosolutions_demo]impossible to modify an existing context

### ISSUE THREAD

**Issue by sigrmed** [georchestra/mapstore2-georchestra#198] opened 2020-03-09 12:00 UTC
I tried to modify https://georchestra.geo-solutions.it/mapstore/#/admin/context-creator/133
I'm connected as testadmin .
I can modify the context properties but i can't modify the context himself (blank page)
![image](https://user-images.githubusercontent.com/60706935/76210820-2f87aa00-6205-11ea-9b5f-e1811090965e.png)

**Comment by catmorales** [comment] 2020-03-09 12:01
Sorry i signed with another account .

**Comment by landryb** [comment] 2020-03-09 12:41
duplicate of #170 ? i've never been able to edit a context once it has been created

**Comment by catmorales** [comment] 2020-03-09 13:00
Yes I agree , it's the same . I close this one and i will complete #170

**Closed by catmorales** 2020-03-09 13:00 UTC
Labels: User feedback
