### ISSUE TITLE
Issues with the latest update of DEV branch

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#528] opened 2022-05-10 12:41 UTC
Few important findings after a really quick test in GeoSolutions DEV:

1. The new sidebar is not visible in the default viewer (also for new maps created) and also the burger menu is not available

![image](https://user-images.githubusercontent.com/1280027/167631351-9f6e83cb-7939-4b5a-97b7-91ea9a53a6cd.png)

2. Opening the wizard for an existing context that should have all plugins in it, they are not selected in the wizard

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/651970aa-329a-4bfa-bf99-9c426b251f28)

3. If you try to add all of them to the _Enabled Plugins_ an exception is raised in console

```
geOrchestra.js?ef6fd0257f32c5962092:2 Error in epic "enablePluginsEpic". Original error: TypeError: Cannot read properties of null (reading 'mandatory')
    at n (geOrchestra.js?ef6fd0257f32c5962092:2:1720546)
    at geOrchestra.js?ef6fd0257f32c5962092:2:1720949
    at Array.forEach (<anonymous>)
    at u (geOrchestra.js?ef6fd0257f32c5962092:2:1720936)
    at geOrchestra.js?ef6fd0257f32c5962092:2:1720996
    at Array.forEach (<anonymous>)
    at t.project (geOrchestra.js?ef6fd0257f32c5962092:2:1720983)
    at t._next (geOrchestra.js?ef6fd0257f32c5962092:2:8991274)
    at t.next (geOrchestra.js?ef6fd0257f32c5962092:2:8861317)
    at t._next (geOrchestra.js?ef6fd0257f32c5962092:2:8949128)
    at t.next (geOrchestra.js?ef6fd0257f32c5962092:2:8861317)
    at t.next (geOrchestra.js?ef6fd0257f32c5962092:2:8858195)
    at geOrchestra.js?ef6fd0257f32c5962092:2:8823194
    at geOrchestra.js?ef6fd0257f32c5962092:2:8823180
    at geOrchestra.js?ef6fd0257f32c5962092:2:8824015
    at t.dispatch [as _next] (geOrchestra.js?ef6fd0257f32c5962092:2:8831275)
(anonimo) @ geOrchestra.js?ef6fd0257f32c5962092:2
geOrchestra.js?ef6fd0257f32c5962092:2 Uncaught TypeError: Cannot read properties of null (reading 'mandatory')
    at n (geOrchestra.js?ef6fd0257f32c5962092:2:1720546)
    at geOrchestra.js?ef6fd0257f32c5962092:2:1720949
    at Array.forEach (<anonymous>)
    at u (geOrchestra.js?ef6fd0257f32c5962092:2:1720936)
    at geOrchestra.js?ef6fd0257f32c5962092:2:1720996
    at Array.forEach (<anonymous>)
    at t.project (geOrchestra.js?ef6fd0257f32c5962092:2:1720983)
    at t._next (geOrchestra.js?ef6fd0257f32c5962092:2:8991274)
    at t.next (geOrchestra.js?ef6fd0257f32c5962092:2:8861317)
    at t._next (geOrchestra.js?ef6fd0257f32c5962092:2:8949128)
    at t.next (geOrchestra.js?ef6fd0257f32c5962092:2:8861317)
    at t.next (geOrchestra.js?ef6fd0257f32c5962092:2:8858195)
    at geOrchestra.js?ef6fd0257f32c5962092:2:8823194
    at geOrchestra.js?ef6fd0257f32c5962092:2:8823180
    at geOrchestra.js?ef6fd0257f32c5962092:2:8824015
    at t.dispatch [as _next] (geOrchestra.js?ef6fd0257f32c5962092:2:8831275)
```

While if you open it, the plugins are present in the viewer context:
https://georchestra.geo-solutions.it/mapstore/#/context/AdvancedContext

**Comment by alexander-fedorenko** [comment] 2022-05-10 21:04
All the issues were caused by misconfiguration in localConfig.json & plugins.js files. All of them are addressed in the latest state of geOrchestra DEV branch.

**Closed** 2022-12-14 17:23 UTC
Labels: Priority: Blocker, Contract #3
