### ISSUE TITLE
Dashboards and Stories

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#326] opened 2021-02-04 08:09 UTC
Maybe I miss it but is it or will it be possible to access Dashboards and Stories functions in the geOrchestra's version of MapStore ?

**Comment by severinmenard** [comment] 2021-02-23 14:13
I would be interested as well to get an answer on this topic

**Comment by jusabatier** [comment] 2021-05-06 07:02
Can we have an answers to this question ?

Having a page like the Dashboard one which list all the contexts a user can access is a good thing to integrate in a website.

**Comment by catmorales** [comment] 2021-05-06 07:40
>list all the contexts a user can access is a good thing to integrate in a website.

I don't know if you mean this.

The "map catalog " (catalogue de cartes) is an option to have applicaton contexts usable by users in mapstore default map (/mapstore). we are ing it 
we are implementing it in the following way:

* create an application context in the context manager with all the desired extensions
* add the extensions "map catalogue" and "save" to it
* open the application context as user
* save the current map (in fact, it saves the map and the extensions)
* make it public (everyone can see it)
* go to the default map  on /mapstore
* open the map catalogue and find the whole application context (maps, base layers and extensions)
* the user can then load it and have the whole environment of this application context

**Comment by jusabatier** [comment] 2021-05-06 08:02
The idea is more to have a list of available contexts for the user based on his roles directly in the website.
I don't want them to open mapstore then open the map catalogue and then open the map they want, it's a too long path.

The way I see it is to have a "My maps" or "Interactive maps" page/link on our website (portal) that list mapstore's available maps without opening mapstore, just a list with title, description and thumb like the dashboard of the default mapstore provide.

**Comment by catmorales** [comment] 2021-05-06 08:23
Ok like the standard mapstore's page.
 You can see the discussion about it on https://github.com/georchestra/mapstore2-georchestra/issues/209#issuecomment-607930390

**Comment by landryb** [comment] 2021-05-06 08:31
> The way I see it is to have a "My maps" or "Interactive maps" page/link on our website (portal) that list mapstore's available maps without opening mapstore, just a list with title, description and thumb like the dashboard of the default mapstore provide.

cant you access that context/maps list via a mapstore rest API ?

**Comment by catmorales** [comment] 2021-05-06 08:40
>cant you access that context/maps list via a mapstore rest API ?

Do you know the method used to do it ?
If it's possible i think everyone could do its own page.


Otherwise, we can discuss it  (a dashboard page of the context applications for users) as an evolution of mapstore2georchestra functonnality ?

**Comment by jusabatier** [comment] 2021-05-06 08:50
I asked about the Dashboard because it exists in vanilla Mapstore and I supposed it's not huge work to simply map this page to an other URL than homepage for mapstore-georchestra.
More over, I understand that the stories functionality is accessed by the dashboard.

The API is also a good solution if it already exists.

**Comment by landryb** [comment] 2021-05-06 12:56
well, when one opens the 'map catalog' window, a request is made to `/mapstore/rest/geostore/extjs/search/category/MAP/***/thumbnail,details,featured?includeAttributes=true&start=0&limit=12` and the json returned by the API seems to describe all the contexts/maps accessible to the current user.. so that should allow creating a 'landing page' for users.

as for the dashboard page itself, dunno if simply enabling the plugin is 'enough' .. https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.Dashboard but part of the original integration requested to geosolution clearly said we wanted the default landing page to be the viewer itself, and not the dashboard, since (at the time?) everyone said it was redundant with the map metadata ppl had made in geonetwork (eg XML md with the link to the wmc previously in mfapp).

as for 'stories', same thing, try enabling the https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.Geostories plugins ?

from my understanding of `js/plugins.js` in this repo, both plugins are enabled/available in the build, so maybe it's just a matter of activating them in `localConfig.js` ? or maybe more is needed.

**Comment by landryb** [comment] 2022-02-07 15:52
duplicate of/solved by #438 :)

**Closed by landryb** 2022-02-07 15:52 UTC
Labels: User feedback
