### ISSUE TITLE
[Contexts] Lost of georchestra's header and  background layers thumbnails in application contexts

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#573] opened 2022-12-06 14:46 UTC
## Environment
 * **Release** :  https://github.com/georchestra/mapstore2-georchestra/commits/2022.02.00-RC3-geOrchestra
 * **Site** : https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/testissue

## Description
![image](https://user-images.githubusercontent.com/4659829/205943681-c83c28ce-33d8-4f69-a5f8-ab195927bc4d.png)

## How to reproduce
* create a new context
* save it and use the shared link to open it in a new window
* we lost the background layer thumbnails and the georchestra header
* same behaviour with CTRL F5 (reload the context)
* 
*Expected Result*
Open the context with all components

*Current Result*
 lost the background layer thumbnails and the georchestra header

- [x] Not browser related
tested on chrome and Mozilla Firefox

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment] 2022-12-06 17:05
@catmorales at a first look it seems something connected to your environment/installation. Are you able to reproduce the same problem in [our instance](https://georchestra.geo-solutions.it/)? Is this happening only to you? What about other installations using the same version?

**Comment by tdipisa** [comment] 2022-12-06 17:19
@catmorales a couple of feedback:

- For the Header I suspect your issue can be connected to [this](https://github.com/georchestra/mapstore2-georchestra/pull/552). Please check/update your localConfig.json in your MS data directory. Probably we simply forgot to document it [here](https://github.com/georchestra/mapstore2-georchestra/releases/tag/2022.02.00-RC1-geOrchestra)
- For the thumbnails I suspect it is a kind of connection issue on your end. I'm not able to reproduce it at the moment
![image](https://user-images.githubusercontent.com/1280027/205979044-c81e212c-0734-4682-b979-95e9fc218202.png)

**Comment by catmorales** [comment] 2022-12-06 18:04
> For the Header I suspect your issue can be connected to https://github.com/georchestra/mapstore2-georchestra/pull/552

Ok i will try to add it

**Comment by catmorales** [comment] 2022-12-06 18:16
Indeed, I didn't have this setting, it seems to have solved the header problem, I'll test more tomorrow.
On the other hand, I don't know what happens with the thumbnails, I'll see tomorrow

**Comment by catmorales** [comment] 2022-12-07 17:44
For the header, it's OK . 
For the thumbnails , I don't understand because the map configurations seems good , it contains the thumbnails properties.
![image](https://user-images.githubusercontent.com/4659829/206254482-5c058eb0-19db-4bb3-8c55-0378c6baac94.png)

**Comment by catmorales** [comment] 2022-12-12 13:32
@jusabatier et @landryb 
Do you have the same behaviour with the RC3 release ?

**Comment by jusabatier** [comment] 2022-12-12 13:45
No, we don't have this behavior on our platform.

**Comment by catmorales** [comment] 2022-12-12 15:13
> I suspect it is a kind of connection issue on your end

We did more tests and it seems that the times to upload the mapcontexts is too short to load the thumbnails. 

We dont-have this issue with /mapstore where configuration is stored in json files and not in the database.
We are on a 9.6 release of Postgres in the database. Perhaps we should be look at the database indexes. 
I'll check with the releases notes of mapstore 2022.02.xx's migration

Do you have some recomendations ?

**Comment by catmorales** [comment] 2022-12-13 13:41
>because you are using the UserSession plugin more extensively in your platform.

Yes we always use it.

>What we can do now is try removing the Background Selector from the modular plug-in configuration to see if this is responsible for making this issue more evident

Ok we can try

**Comment by tdipisa** [comment] 2022-12-13 14:17
@catmorales we have merged on master [this PR](https://github.com/georchestra/mapstore2-georchestra/pull/578) that solves the issue you have as I've indicated in my previous comment. If you want you can test deploying the image corresponding to the master branch so that then we will backport to 2022.02.xx ready for the final release.

**Comment by jusabatier** [comment] 2022-12-13 14:25
Will you upgrade to the last Mapstore's upstream 2022.02.xx branch before final release ?

**Comment by tdipisa** [comment] 2022-12-13 14:33
@jusabatier thank you for asking. It is not expected in theory. Since you have tested during the VSR phase with a specific MS revision (the one of RC3) we should do the final release of mapstore2-georchestra with the same. But well, we are talking about a minor version update therefore there should not be problems. Anyway please let me know for what you are asking this, a specific bug fix maybe we have done in the meantime?

**Comment by jusabatier** [comment] 2022-12-13 14:38
Effectively, currently this fix : https://github.com/georchestra/mapstore2-georchestra/issues/572

We try to setup contexts to allow our users to provide data and this bug make it difficult.

More generally, if it's not too complicate for you I think it's a good point to retrieve all bug fixes available from 2022.02.xx upstream branch.

**Comment by tdipisa** [comment] 2022-12-14 10:44
@catmorales we have done the backport with this https://github.com/georchestra/mapstore2-georchestra/pull/579

**Comment by catmorales** [comment] 2022-12-14 14:38
> we have done the backport with this https://github.com/georchestra/mapstore2-georchestra/pull/579

@offtherailz could you, please,  update the docker image https://hub.docker.com/layers/geosolutionsit/mapstore2-georchestra/2022.02.xx/images/sha256-da3cefd2b898ec8f09b99bae594e83bf387c88106b57f5e232c483aa2446e401?context=explore ?

**Comment by tdipisa** [comment] 2022-12-14 14:58
@catmorales our CI/CD is building now to generate the new image. I will let you know when done.

**Comment by tdipisa** [comment] 2022-12-14 17:28
@catmorales done 
https://hub.docker.com/layers/geosolutionsit/mapstore2-georchestra/2022.02.xx/images/sha256-3f842609de98b07aa3c61f58d81c6c2e11d49a99b153452eeaaa92085ecbdb64?context=explore

**Closed** 2022-12-15 09:31 UTC
Labels: Contract #3
